# Generated by Django 3.0.3 on 2020-03-04 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapi', '0003_auto_20200304_2108'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalist',
            name='birth_date',
            field=models.DateField(null=True),
        ),
    ]
